name: deploy to dev
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Deploy to developement
      run: |
        cd /home/smaug/Spiritus/dev
        git stash
        git pull origin dev
        npm install
        pm2 reload ecosystem.config.js