name: deploy to dev
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: pull
      run: |
        cd /home/smaug/Spiritus/dev
        git stash
        git pull origin master
        npm install
