name: deploy to dev
on:
  push:
    branches: [ dev ]
jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: pull
      run: |
        cd /home/smaug/Spiritus/dev
        git pull origin master
        npm install